### ISSUE TITLE
kachery-cloud-init get libffi.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GandalfTGrey** [flatironinstitute/spikeforest#22]
~$: kachery-cloud-init
Traceback (most recent call last):
  File "/home/lim/.conda/envs/spike/bin/kachery-cloud", line 6, in <module>
    cli()
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/kachery_cloud/cli.py", line 13, in init
    kc.init()
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/kachery_cloud/init.py", line 35, in init
    client_info = _get_client_info()
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/kachery_cloud/init.py", line 26, in _get_client_info
    response = _kacherycloud_request(payload)
  File "/home/lim/.conda/envkachery-cloud-inits/spike/lib/python3.8/site-packages/kachery_cloud/_kacherycloud_request.py", line 16, in _kacherycloud_request
    'signature': _sign_message_as_client(payload)
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/kachery_cloud/_client_keys.py", line 61, in _sign_message_as_client
    return _sign_message(msg, public_key_hex, private_key_hex)
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/kachery_cloud/_client_keys.py", line 111, in _sign_message
    privk = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(private_key_hex))
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/ed25519.py", line 61, in from_private_bytes
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/lim/.conda/envs/spike/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

**Comment by magland** [comment]
Thanks for the report. I have not seen this error before. Seems an issue with finding the right version of libffti. cryptography package uses cffi for running C code.

Would be really helpful if you could you give some further information about your system.

OS including version?

Are you using miniconda? anaconda?

Output of `conda --version`

Output of `conda list` so we can see what versions of the packages you have installed.

Thanks!

**Comment by GandalfTGrey** [comment]
Thanks for your reply! Problem fixed, it is issue with version of libffi indeed.
Best regards

**Comment by magland** [comment]
@GandalfTGrey great! What did you do to fix it? (in case someone else has a similar problem)

**Comment by GandalfTGrey** [comment]
I was using Ubuntu18.04 and got libffi6 installed instead of libffi7, so I using this install libffi7 
```
wget http://es.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
sudo dpkg -i libffi7_3.3-4_amd64.deb
```
refer to here
[[libffi.so.7: cannot open shared object file: No such file or directory](https://askubuntu.com/questions/1286772/libffi-so-7-cannot-open-shared-object-file-no-such-file-or-directory)]

**Comment by magland** [comment]
Thanks!
