### ISSUE TITLE
Problem in test_mountainsort4.py : module 'spikeforest' has no attribute '__version__'

### ISSUE THREAD

**Issue by ZoeChen96** [flatironinstitute/spikeforest#27]
Hi there,

I installed the spikeforest by using the method you suggest, and I can run all the 4 sample codes you provide. However, when I run the test python file: test_mountainsort4.py, I encounter the error:

Error running mountainsort4
Traceback (most recent call last):
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 225, in run_from_folder
    SorterClass._run_from_folder(output_folder, sorter_params, verbose)
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/sorters/mountainsort4/mountainsort4.py", line 91, in _run_from_folder
    recording = load_extractor(output_folder / 'spikeinterface_recording.json')
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/core/base.py", line 906, in load_extractor
    return BaseExtractor.load(file_or_folder_or_dict, base_folder=base_folder)
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/core/base.py", line 545, in load
    extractor = BaseExtractor.from_dict(d, base_folder=base_folder)
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/core/base.py", line 372, in from_dict
    extractor = _load_extractor_from_dict(d)
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/core/base.py", line 844, in _load_extractor_from_dict
    if not _check_same_version(class_name, dic['version']):
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/core/base.py", line 877, in _check_same_version
    current_version = parse(imported_module.__version__)
AttributeError: module 'spikeforest' has no attribute '__version__'

And also:
Traceback (most recent call last):
  File "/xxx/spikeforest/examples/test_mountainsort4.py", line 48, in <module>
    main()
  File "/xxx/spikeforest/examples/test_mountainsort4.py", line 32, in main
    sorting: si.BaseSorting = ss.run_mountainsort4(
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 656, in run_mountainsort4
    return run_sorter('mountainsort4', *args, **kwargs)
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 143, in run_sorter
    return run_sorter_local(**common_kwargs)
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 163, in run_sorter_local
    SorterClass.run_from_folder(output_folder, raise_error, verbose)
  File "/xxx/envs/si_full/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 261, in run_from_folder
    raise SpikeSortingError(
spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in mountainsort4_output/spikeinterface_log.json

The second one seems the same as the first one.

PS: My installed version:
spikeforest: 0.12.5
python: 3.19.3
numpy: 1.23.4
spikeinterface:0.96.1
kachery-cloud: 0.3.6

Thank you in advance for your help!

**Comment by magland** [comment]
Hi @ZoeChen96 . Thanks for posting this issue. I am going to remove that example from this repo because it is no longer working. Instead please refer to the spikeinterface project which will provide instructions on how to do spike sorting for the SI objects obtained from this repo.

**Comment by ZoeChen96** [comment]
Thanks magland!
