### ISSUE TITLE
How to get the uri for SYNTH_MONOTRODE

### ISSUE THREAD

**Issue by ZoeChen96** [flatironinstitute/spikeforest#28]
Hi there,
I would like to use the SYNTH_MONOTRODE datasets for some algorithms. I checked the list_all_recordings.py, but I can't find the uri for this dataset. It only shows the path to hybrid_janelia_uri, which is 
'sha1://43298d72b2d0860ae45fc9b0864137a976cb76e8?spikeforest-recordings.json'
I wonder how can I find the uri for SYNTH_MONOTRODE.

Besides, I found the project has the version2 in https://github.com/flatironinstitute/spikeforest2. I would like to try new algorithms for existing datasets. Which package do you recommend, spikeforest or spikeforest2?

Thank you in advance for answering!

**Comment by magland** [comment]
Hi @ZoeChen96, sorry about the name of the spikeforest2 repo. I have now added a warning at the top of that README saying it's obsolete and to use this (spikeforest) repo instead.

I will prepare the link for the SYNTH_MONOTRODE datasets and get back to you shortly.

**Comment by magland** [comment]
Hi again @ZoeChen96.

I have now added synth_monotrode_uri in the example scripts. Let me know if you encounter any trouble.

**Comment by ZoeChen96** [comment]
Hi @magland ,

Thanks a lot for the effort! I got the synth_monotrode_uri now. But I have 3 more issues:

1) I can't do `recording = R.get_recording_extractor()` for recording 'C_Easy1_noise005'. It gives the error which is:

> Traceback (most recent call last):
>   File "/xxx/spikeforest/examples/quiroga_single_tb.py", line 24, in <module>
>     recording = R.get_recording_extractor()
> 
>   File "/xxx/spikeforest/spikeforest/load_spikeforest_recordings/SFRecording.py", line 41, in get_recording_extractor
>     return load_recording_extractor(self.recording_object)
> 
>   File "/xxx/spikeforest/spikeforest/load_extractors/load_recording_extractor.py", line 8, in load_recording_extractor
>     return load_recording_extractor(dict(
> 
>   File "/xxx/spikeforest/spikeforest/load_extractors/load_recording_extractor.py", line 27, in load_recording_extractor
>     return MdaRecordingExtractorV2(raw_path=raw_path, params=params, geom=geom)
> 
>   File "/xxx/spikeforest/spikeforest/load_extractors/MdaRecordingExtractorV2/MdaRecordingExtractorV2.py", line 34, in __init__
>     self.set_dummy_probe_from_locations(np.array(geom))
> 
>   File "/xxx/anaconda43/envs/si_full/lib/python3.9/site-packages/spikeinterface/core/baserecordingsnippets.py", line 261, in set_dummy_probe_from_locations
>     ndim = locations.shape[1]
> IndexError: tuple index out of range


2) I can't get the uri for  SYNTH_MONOTRODE's sorter's output. Which means in file [https://github.com/flatironinstitute/spikeforest/blob/main/examples/load_extractor_for_sorting_output.py](url) I did not find the uri.

3) actually, even if the 1) works, I don't know what I should do to apply a sorter on it (like you do on the website [https://spikeforest.flatironinstitute.org/](url) ) . Where can I find the guideline for that?

Thanks a lot,
Yunzhu

**Comment by magland** [comment]
Thanks @ZoeChen96 for the report!

I fixed (1) (it was an edge case for monotrodes). So pip install `--upgrade` the latest version.

For (2) I will work on preparing the sorting outputs for this.

For (3) I will refer you to the [spikeinterface](https://github.com/spikeinterface/spikeinterface) project

**Comment by magland** [comment]
Regarding (2) the URI for sorting outputs with synth monotrodes is here:
https://github.com/flatironinstitute/spikeforest/blob/main/examples/list_all_sorting_outputs.py

**Comment by magland** [comment]
Oh sorry, I see what the problem is. The issue is that the uri parameter is not exposed here:
https://github.com/flatironinstitute/spikeforest/blob/main/spikeforest/load_spikeforest_sorting_outputs/load_spikeforest_sorting_output.py

I will get to fixing that, but you should be able to just put in uri as an additional parameter and pass it through to load_spikeforest_sorting_outputs as follows

```python
def load_spikeforest_sorting_output(*, study_name: str, recording_name: str, sorter_name: str, uri: Union[str, None]=None):
    all_sorting_outputs = load_spikeforest_sorting_outputs(uri=uri) # not sure if this is exactly right.
```

If you make that change and it works, please submit a PR. thx

**Comment by ZoeChen96** [comment]
Hi Magland,

Thanks for your prompt response! I tried to upgrade by using `pip install --upgrade spikeforest` and have the version 0.12.6. After doing this, I encounter the following issue: 

>  File "/xxx/spikeforest/examples/list_all_recordings.py", line 2, in <module>
>     import spikeforest as sf
>   File "/xxx/anaconda43/envs/si_full/lib/python3.9/site-packages/spikeforest/__init__.py", line 5, in <module>
>     from .load_spikeforest_sorting_outputs.load_spikeforest_sorting_outputs import load_spikeforest_sorting_outputs
> ModuleNotFoundError: No module named 'spikeforest.load_spikeforest_sorting_outputs'

I tried to use the history version like 0.12.5 or 0.12.4 but none of them works now...
Besides, I used to install this package by `git pull` or something. This may be really a easy question: What's the difference between the git pull and pip install? Will it be any problem now if I delete the files that I git pull before? I think it will not be influenced because I assume the `pip install` will save the module in another place, is that correct?

**Comment by jsoules** [comment]
Hi Yunzhu,

Thanks for your interest in using SpikeForest--sorry you've been hitting some snags.

To answer the questions you asked--there's two main ways to install Python packages with `pip`:
-  If you do `pip install <PACKAGENAME>` the pip utility will download the latest published version of the package from the Python package repository ([PyPI](https://pypi.org/))
- You can also install a package directly from its source code on your local file system with `pip install -e /path/to/package/code`

When you were installing the version you got with `git pull`, you were probably installing it locally using `pip -e`. If you just list the package name, you get the published version, which might not be the latest code in the repository.

---

I tried to reproduce the problem you reported by creating a new [Conda](https://docs.conda.io/en/latest/) environment and installing the published version of spikeforest:

```bash
$ conda create --name test python=3.9
$ conda activate test
$ pip install --upgrade spikeforest ipython
$ cd src/spikeforest # (This is where I have this github repo cloned)
$ python ./examples/list_all_recordings.py
```

(I'm describing this in detail because I'm jumping into the middle of your conversation, so I want to make sure I understand exactly what steps you're doing--apologies if I'm being a little tedious!)

If I do the steps above, I get the same error you did--there's a problem loading the spikeforest module. Most likely this means that the published version of the `spikeforest` package in the Python package repository is out of date. I'll open an issue for us to publish the current one (we might need to check a few things first).

In the meantime, it should work if you install locally again.

- Clone this repo (I put my copy in `~/src/spikeforest` so I'm going to use that in the steps below)
  - Or, if you already have it, do a `git pull` to make sure that you have the latest code. Then:
- `$ cd ~/src/spikeforest`
- `$ pip install -e .`
- `$ python ./examples/list_all_recordings.py`

I just tried all that in the same `test` conda environment, and then `list_all_recordings.py` prints a bunch of stuff to the screen like it's supposed to.

So, try that and let us know what further problems you encounter!

best,
Jeff

**Comment by ZoeChen96** [comment]
Hi Jeff,

Thanks for your thorough explanations! It's not tedious, instead it helped quite a lot. 
I tried with `pip install -e .` and I saw no errors. I will try tomorrow about my previous problem with the MONOTRODE datasets and spikeinterface. Thanks a lot!

Best regards,
Yunzhu

**Comment by jsoules** [comment]
My pleasure! Let us know how it goes and if you have any further issues.

Given the holiday weekend we probably won't be able to get back to you until Monday, but we'll be happy to help out further then.
