### ISSUE TITLE
issue regarding importing spikeforest and/or spikeinterface

### ISSUE THREAD

**Issue by GanshengT** [flatironinstitute/spikeforest#41]
Dear developers,

I clone the git repository and install spikeforest and spikeinterface. However, when I tried to run the example py files from the terminal, I encountered an import error.

(spikeInterface) ganshengtan@Ganshengs-MacBook-Pro examples % ls
create_workspaces.py			load_console_out_for_sorting_output.py
download_all_raw_recordings_data.py	load_extractor_for_sorting_output.py
list_all_recordings.py			load_extractors_for_recording.py
list_all_sorting_outputs.py		sorting_old
(spikeInterface) ganshengtan@Ganshengs-MacBook-Pro examples % python3 list_all_recordings.py 
Traceback (most recent call last):
  File "/......../spikeForest_syn/spikeforest/examples/list_all_recordings.py", line 2, in <module>
    import spikeforest as sf
  File "/......../spikeForest_syn/spikeforest/spikeforest/__init__.py", line 1, in <module>
    from .load_extractors.load_recording_extractor import load_recording_extractor
  File "/......./spikeForest_syn/spikeforest/spikeforest/load_extractors/__init__.py", line 1, in <module>
    from .load_recording_extractor import load_recording_extractor
  File "/......./spikeForest_syn/spikeforest/spikeforest/load_extractors/load_recording_extractor.py", line 2, in <module>
    from .MdaRecordingExtractorV2.MdaRecordingExtractorV2 import MdaRecordingExtractorV2
  File "/......./spikeForest_syn/spikeforest/spikeforest/load_extractors/MdaRecordingExtractorV2/MdaRecordingExtractorV2.py", line 2, in <module>
    from spikeinterface.core.core_tools import write_binary_recording
ImportError: cannot import name 'write_binary_recording' from 'spikeinterface.core.core_tools' (/....../spikeForest_syn/spikeinterface/src/spikeinterface/core/core_tools.py)

**Comment by GanshengT** [comment]
The issue seems to be that spikeinterface moves write_binary_recording to spikeinterface.core. write_binary_recording

**Comment by magland** [comment]
@GanshengT Thanks for identifying that issue. I pushed the change.
